---
extends: airbnb-base
env:
  node: true
  es6: true
rules:
  no-unused-vars:
    - error
    -
      argsIgnorePattern: "_.*"
      varsIgnorePattern: "_.*"
  no-console:
    - off
  no-use-before-define:
    - error
    - nofunc
  object-curly-newline:
    - error
    -
      ObjectExpression:
        multiline: true
      ObjectPattern:
        # Don't discourage long-ish lists of named powerful objects.
        multiline: true
        minProperties: 5
