---
extends: airbnb-base
env:
  node: true
  es6: true
rules:
  no-undef:
    - off
  no-unused-vars:
    - off
    -
      argsIgnorePattern: "_.*"
      varsIgnorePattern: "_.*"
  no-console:
    - off
  no-var:
    - off
  vars-on-top:
    - off
  strict:
    - off
  quotes:
    - off
  prefer-template:
    - off
  semi:
    - off
  comma-dangle:
    - off
  arrow-body-style:
    - off
  arrow-parens:
    - off
  object-shorthand:
    - off
  object-curly-spacing:
    - off
  object-curly-newline:
    - off
  indent:
    - off
  no-multi-spaces:
    - off
  spaced-comment:
    - off
  no-multiple-empty-lines:
    - off
  space-in-parens:
    - off
  padded-blocks:
    - off
  keyword-spacing:
    - off
  space-before-blocks:
    - off
  newline-per-chained-call:
    - off
